#ifndef __FLASH_PARTITION_H__
#define __FLASH_PARTITION_H__

// 设备信息存储地址和大小
#define DEVICE_INFO_ADDR 0x00000000
#define DEVICE_INFO_SIZE 0x1000
// 设备信息备份存储地址和大小
#define DEVICE_INFO_BACKUP_ADDR (DEVICE_INFO_ADDR + DEVICE_INFO_SIZE)
#define DEVICE_INFO_BACKUP_SIZE DEVICE_INFO_SIZE

// 参数配置存储地址和大小
#define PARAM_CONFIG_ADDR (DEVICE_INFO_BACKUP_ADDR + DEVICE_INFO_BACKUP_SIZE)
#define PARAM_CONFIG_SIZE 0x1000
// 参数配置备份存储地址和大小
#define PARAM_CONFIG_BACKUP_ADDR (PARAM_CONFIG_ADDR + PARAM_CONFIG_SIZE)
#define PARAM_CONFIG_BACKUP_SIZE PARAM_CONFIG_SIZE

// 警告信息存储地址和大小
#define WARNING_INFO_ADDR 0x00100000
#define WARNING_INFO_SIZE 0x00100000

//OTA下载固件信息区域
#define OTA_FW_INFO_ADDR (WARNING_INFO_ADDR + WARNING_INFO_SIZE) 
#define OTA_FW_INFO_SIZE 0x00000400

//下载区域地址和大小
#define DOWNLOAD_ADDR (OTA_FW_INFO_ADDR + OTA_FW_INFO_SIZE)
#define DOWNLOAD_SIZE (0x00200000 - OTA_FW_INFO_SIZE)

//LOG存储地址和大小
#define LOG_ADDR (DOWNLOAD_ADDR + DOWNLOAD_SIZE)
#define LOG_SIZE 0x00C00000

//BOOTLOADER起始地址
#define BOOTLOADER_ADDRESS 0x08000000
//BOOT INFO 存储地址和大小
#define BOOT_INFO_ADDR 0x08007800
#define BOOT_INFO_SIZE 0x00000800
//APP0 存储地址和大小
#define APP0_ADDR 0x08008000
#define APP0_SIZE 0x00078000
//BACKUP APP 存储地址和大小
#define APP_BACKUP_ADDR (APP0_ADDR + APP0_SIZE)
#define APP_BACKUP_SIZE 0x80000

#endif